package com.techiness.progressdialoglibrary

import com.techiness.progressdialoglibrary.ProgressDialogDslContract

sealed interface IndeterminateProgressDialogDslContract: ProgressDialogDslContract {

}