name: Generate Docs and Deploy to GH Pages

on:
  release:
    types: [released]
#   Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 11
          distribution: adopt
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0
        with:
          gradle-version: 7.4.2
      - name: Generate KDoc and JavaDoc
        if: ${{github.event_name == 'release'}}
        run: gradle :progressdialoglibrary:dokkaHtml :progressdialoglibrary:dokkaJavadoc
      - name: Format Version Tag Name
        uses: actions/github-script@v7.0.1
        id: format_version_tag
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
      - name: Deploy KDoc to GH Pages with Version
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: progressdialoglibrary/build/dokka/html
          target-folder: kotlin/${{ steps.format_version_tag.outputs.no-v }}/
      - name: Deploy KDoc to GH Pages as Latest
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: progressdialoglibrary/build/dokka/html
          target-folder: kotlin/latest/    
      - name: Deploy JavaDoc to GH Pages with Version
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: progressdialoglibrary/build/dokka/javadoc
          target-folder: java/${{ steps.format_version_tag.outputs.no-v }}/
      - name: Deploy JavaDoc to GH Pages as Latest
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: progressdialoglibrary/build/dokka/javadoc
          target-folder: java/latest/
